---
- name: Prepare
  hosts: all
  vars:
    pip_install_packages:
      - name: more_itertools<6.0
      - name: docker
      - name: docker_compose
  tasks:
    - name: install dependencies
      package:
        name: "{{ item }}"
      with_items:
        - python-devel
        - python-virtualenv
        - gcc
        - libffi-devel
    - include_role:
        name: geerlingguy.pip
    # see: https://github.com/ansible/molecule/issues/1568
    - name: create docker.sock
      raw: touch /var/run/docker.sock
      become: true
      changed_when: false
    - name: move docker.sock from tmp
      raw: mount --move /tmp/docker.sock /var/run/docker.sock
      become: true
      changed_when: false
