# The upstream image includes the Ansible plugin but no
# Ansible command, so let's fix that in another layer.
FROM rundeck/rundeck:3.1.2

RUN sudo apt-get update && sudo apt-get install -y ansible \
	&& sudo apt-get install -y docker.io && sudo rm -rf /var/lib/apt/lists/*